### ISSUE TITLE
Use PrecompileTools to improve load time

### ISSUE THREAD

**Issue by plerouxanyon** [SnowflurrySDK/Snowflurry.jl#136]
PrecompileTools allows you to specify workflows that can be added to the precompilation steps. This allows more of the compilation to be moved to the precompilation step, improving responsiveness when using Snowflake.

See https://julialang.github.io/PrecompileTools.jl/stable/ for more information.

**Comment by npoirie1** [comment]
SnoopPrecompile is now deprecated. PrecompileTools should be used instead. It works best with Julia 1.9 and higher.

See [https://julialang.github.io/PrecompileTools.jl/stable/](https://julialang.github.io/PrecompileTools.jl/stable/) for more details.

**Comment by plerouxanyon** [comment]
This issue has been closed by #275
